"use client";
import Image from "next/image";
import { useRef, useState } from "react";
import { Icon } from "@/components/icon";
import type { Media } from "./data";
export function Gallery({ media, name }: { media: Media[]; name: string }) {
  const [active, setActive] = useState(0); const dialog = useRef<HTMLDialogElement>(null);
  if (!media.length) return <div className="gallery-empty"><Icon name="photo" /><p>Este trabajo todavía no tiene fotografías.</p></div>;
  const photo = media[active];
  function change(delta: number) { setActive((previous) => (previous + delta + media.length) % media.length); }
  return <section className="gallery" aria-label="Fotografías del trabajo"><button className="gallery-main" onClick={() => dialog.current?.showModal()} aria-label={`${active + 1} / ${media.length} · Ampliar fotografía`}><Image unoptimized src={`/app/api/photos/${photo.id}`} width={photo.width ?? 1080} height={photo.height ?? 1350} alt={`${name}, fotografía ${active + 1}`} priority /><span className="gallery-count">{active + 1} / {media.length} · Ampliar</span></button><div className="gallery-thumbs">{media.map((item, index) => <button key={item.id} className={index === active ? "active" : ""} onClick={() => setActive(index)} aria-label={`Ver fotografía ${index + 1}`} aria-pressed={index === active}><Image unoptimized src={`/app/api/photos/${item.id}`} width={120} height={120} alt="" /></button>)}</div><dialog ref={dialog} className="image-dialog" onClick={(event) => { if (event.target === event.currentTarget) dialog.current?.close(); }} onKeyDown={(event) => { if (event.key === "ArrowRight") change(1); if (event.key === "ArrowLeft") change(-1); }} aria-label="Fotografía ampliada"><div className="dialog-toolbar"><span>{active + 1} de {media.length}</span><button className="icon-button" aria-label="Cerrar fotografía" onClick={() => dialog.current?.close()}><Icon name="close" /></button></div><Image unoptimized src={`/app/api/photos/${photo.id}?original=1`} width={photo.width ?? 1080} height={photo.height ?? 1350} alt={`${name}, fotografía ${active + 1}`} />{media.length > 1 && <div className="dialog-navigation"><button className="button secondary" onClick={() => change(-1)}><Icon name="arrow" />Anterior</button><button className="button secondary" onClick={() => change(1)}>Siguiente<Icon name="arrow" style={{ transform: "rotate(180deg)" }} /></button></div>}</dialog></section>;
}
